// <auto-generated />
namespace Royaya.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class balancezerodate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(balancezerodate));
        
        string IMigrationMetadata.Id
        {
            get { return "202003011707194_balancezerodate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
