//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoyayaControlPanel.com.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Dreams.
        /// </summary>
        public static string Active_dreams {
            get {
                return ResourceManager.GetString("Active_dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Dream.
        /// </summary>
        public static string Add_dream {
            get {
                return ResourceManager.GetString("Add_dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Path.
        /// </summary>
        public static string Add_path {
            get {
                return ResourceManager.GetString("Add_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Message.
        /// </summary>
        public static string AddNewMessage {
            get {
                return ResourceManager.GetString("AddNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Ratio.
        /// </summary>
        public static string AddNewRatio {
            get {
                return ResourceManager.GetString("AddNewRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dreams.
        /// </summary>
        public static string All_Dreams {
            get {
                return ResourceManager.GetString("All_Dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string All_Users {
            get {
                return ResourceManager.GetString("All_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Ratio.
        /// </summary>
        public static string BalanceRatio {
            get {
                return ResourceManager.GetString("BalanceRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC FUNCTIONS.
        /// </summary>
        public static string BASIC_FUNCTIONS {
            get {
                return ResourceManager.GetString("BASIC_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us Messages.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Users.
        /// </summary>
        public static string DeletedUsers {
            get {
                return ResourceManager.GetString("DeletedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Dreams.
        /// </summary>
        public static string Done_dreams {
            get {
                return ResourceManager.GetString("Done_dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dreams.
        /// </summary>
        public static string Dreams {
            get {
                return ResourceManager.GetString("Dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation Paths.
        /// </summary>
        public static string Interpretation_Paths {
            get {
                return ResourceManager.GetString("Interpretation_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreters.
        /// </summary>
        public static string Interpreters {
            get {
                return ResourceManager.GetString("Interpreters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreters List.
        /// </summary>
        public static string Interpreters_List {
            get {
                return ResourceManager.GetString("Interpreters_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Users.
        /// </summary>
        public static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presonal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio For Each Path.
        /// </summary>
        public static string RatioForEachPath {
            get {
                return ResourceManager.GetString("RatioForEachPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string User_List {
            get {
                return ResourceManager.GetString("User_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string User_List_All {
            get {
                return ResourceManager.GetString("User_List_All", resourceCulture);
            }
        }
    }
}
